#!/bin/sh

VAULT_PATH=/opt/maidsafe/sbin/vault

if [ ! -f $VAULT_PATH ] ; then
  echo "vault executable is missing at $VAULT_PATH" >&2
  exit 1
fi
ln -s $VAULT_PATH /usr/bin/maidsafe_vault
/usr/sbin/update-rc.d vault defaults
/etc/init.d/vault start

exit 0
