#!/bin/bash

set -x -e

cargo clippy "$@" --all-targets
cargo clippy "$@" --all-targets --features=mock_base
cargo clippy "$@" --all-targets --features=mock_serialise
cargo clippy "$@" --all-targets --features=mock
